### PR TITLE
Fixes from DB 2017-2018

### PR DESCRIPTION
**Pull request by dominicbeesley**
Hi Spuddy, I'm new to this GitHub lark but here's my go at creating a Pull request.

It's a few fixes / updates I've been slowly adding to TubeHost over the past 6 months or so. 

D

Added *TYPE - not sure how useful this is?
FIX: OSFILE needs to generate an error for file not found _except 5/6_ - I think!?
FIX: OSGBPB - wrong debug message
FIX: OSGBPB - read 4/5 was not correctly updating local copy of file {ptr}
FIX: OSGBPB - read directories was returning files from other directories

### CODE REVIEW

**Comment by sweharris** [comment]
Thanks for the updates!

Hmm, you have a `.bak` file as part of the pull request.  That should have been omitted from the commit and push.  I've made that mistake in the past.

Re OSFILE: JGH and I had a discussion on this; the spec says return A=0 if the object doesn't exist.  It should not error (A=0 == Object not found; A=1 == File found; A=2 == Directory found).  The code did originally error out but JGH convinced me otherwise... and I think I did a test with DFS that verified he was correct.

I'll look at the other changes when I get home.

I probably won't take the pull request as is, but I'll look at the diffs and if I like them then I'll manually update the code.

Thanks again!

**Comment by sweharris** [comment]
New functionality and (agreed) bugs added to my master branch.  Closed this pull request without merging.

**Comment by dominicbeesley** [comment]
Thanks, I'm new to this GitHub lark, I'll try and be more careful in future with .bak files and the like. I'm more used to SVN where I explicitly add things!

**Comment by sweharris** [comment]
I'm not a git expert, either.  Learning as I go!  With git, you do `git commit file1 file2` (or `git add file1 file2 ; git commit`) to explicitly include files, which you can then `git push`.  If you used the `-a` flag then you've told git to "add all files"... which includes new files.  I'm guessing that's where the `.bak` file came from.

**Pull request closed without merging**
