### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by dominicbeesley**
Hi, it's been a while since I tweaked this. I spotted a bug with OSFIND/close this morning - it always closed all files.

### CODE REVIEW

**Comment by sweharris** [comment]
Hmm somehow this pull is against an older version of the cold and includes changes you've previously made (eg *TYPE).  What I'll do is close this and look at your fork to see what changes you've made, and try and and port them over.

**Comment by dominicbeesley** [comment]
Sorry.  I really don't get on with guthub. I thought I'd got it right this
time!

If there's anything I can do let me know

D

**Comment by sweharris** [comment]
The problem is your fork is based on v0.11 but my tree was based on 0.13 (now 0.14) so whenever you do a pull request it's creating a "diff" set between your 0.11 code and my 0.13.  Essentially it's trying to roll back all the new stuff.

Now there are clever things you can do, to try and bring your fork up to parity with my master.  There may be clever things I can do, but I dunno.  I'm not very good at git, either!

When I make pull requests and they're accepted then typically I just delete my fork and next time I want to work on it I create a new one.  That way I'm up to date :-)   I know it's not the most efficient way, but it works for me!

I've added your fix for CLOSE#, the masking for OSFIND function, but made a different fix for *DIR ('cos the old code would also silently ignore errors like "*DIR UU").

**Comment by sweharris** [comment]
Or it's possible I was doing thing wrongs at my end.  I dunno...

**Comment by sweharris** [comment]
OK, it may have been a combination of the two...  your pull request had stuff from the previous pull request _and_ I hadn't merged a branch properly.  Hey ho...

I don't know what I'm doing with github properly, either!

**Comment by dominicbeesley** [comment]
Thanks. I'll try and rebase my fork... or maybe delete it as you suggest!

D

**Comment by sweharris** [comment]
Please let me know if you find any more issues!  Thanks :-)

**Comment by dominicbeesley** [comment]
Will do. I use it all the time!  I can't believe I only just came across
the close files thing.

I need to finish it off but i have some tweaks to make it run over tcp/ip
too which i didn't finish. But now Roland is selling his Wi-Fi boards it
might become relevant again

**Pull request closed without merging**
